# Generated by Django 5.0.4 on 2024-04-12 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=uuid.UUID('1f5224af-718b-41ea-9b06-82f6a4e5978a'), max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('relation', models.ManyToManyField(blank=True, to='polls.choice')),
            ],
        ),
    ]
